logging:
  #  DEBUG
  #  INFO
  #  WARN
  #  ERROR
  #  PANIC
  #  FATAL
  level:
    root: INFO    # default INFO
    module1.child1: DEBUG
    module1.child2: INFO
    module2: ERROR
  encoding: json # json or console, default json. only encoding, console is plan text encoding
  encoder:
    TimeKey: time
    LevelKey: level
    NameKey: logger
    CallerKey: caller
    MessageKey: msg
    StacktraceKey: stacktrace
  output: # default is console
    file:
      path: /tmp/golang/log.log
      async: false # async output,default false
